# Site settings
title: LiuJie's Blog
email: lj1208@gmail.com
description: "lj1208's blog"
baseurl: ""
url: "http://lj1208.github.io"
twitter_username: lj1208
github_username:  lj1208

# Build settings
markdown: kramdown
permalink: pretty
